name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Gerar o gráfico de contribuição
        uses: Platane/snk@v2
        with:
          github_user_name: 23Edu4rd0
          outputs: dist/snake.svg

      - name: Enviar o gráfico gerado para o repositório
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
